// Package instructorsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package instructorsapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error Стандартное тело ошибки.
type Error struct {
	// Code Машинный код ошибки, например: slot_full, double_booking, slot_cancelled, slot_started, already_cancelled, invalid_code.
	Code string `json:"code"`

	// Details Необязательные машиночитаемые детали для динамических сообщений на клиенте (foundations §6): например, актуальная доступность для E1/E2, чтобы показать «Свободно: N мест» / «Свободно: M досок» без разбора текста message.
	Details *struct {
		// AvailableRentalBoards Сколько прокатных досок реально свободно (для нехватки прокатных досок).
		AvailableRentalBoards *int `json:"available_rental_boards,omitempty"`

		// AvailableSeats Сколько мест реально свободно на момент ошибки (для slot_full / превышения мест).
		AvailableSeats *int `json:"available_seats,omitempty"`
	} `json:"details,omitempty"`

	// Message Человекочитаемое сообщение об ошибке.
	Message string `json:"message"`
}

// Instructor Инструктор, ведущий прогулку.
type Instructor struct {
	// Id Идентификатор инструктора.
	Id openapi_types.UUID `json:"id"`

	// Name Имя инструктора.
	Name string `json:"name"`
}

// InstructorListResponse Постраничный список инструкторов (справочник для фильтра, BS-001).
type InstructorListResponse struct {
	// Items Элементы списка инструкторов.
	Items []Instructor `json:"items"`

	// Meta Метаданные постраничной выдачи.
	Meta PaginationMeta `json:"meta"`
}

// PaginationMeta Метаданные постраничной выдачи.
type PaginationMeta struct {
	// Limit Размер страницы.
	Limit int `json:"limit"`

	// Offset Смещение от начала выборки.
	Offset int `json:"offset"`

	// Total Общее число элементов.
	Total int `json:"total"`
}

// LimitParam defines model for LimitParam.
type LimitParam = int

// OffsetParam defines model for OffsetParam.
type OffsetParam = int

// InternalError Стандартное тело ошибки.
type InternalError = Error

// Unauthorized Стандартное тело ошибки.
type Unauthorized = Error

// ListInstructorsParams defines parameters for ListInstructors.
type ListInstructorsParams struct {
	// Limit Максимальное число элементов в выдаче
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение от начала выдачи
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Справочник инструкторов
	// (GET /instructors)
	ListInstructors(w http.ResponseWriter, r *http.Request, params ListInstructorsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Справочник инструкторов
// (GET /instructors)
func (_ Unimplemented) ListInstructors(w http.ResponseWriter, r *http.Request, params ListInstructorsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListInstructors operation middleware
func (siw *ServerInterfaceWrapper) ListInstructors(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInstructorsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInstructors(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/instructors", wrapper.ListInstructors)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xY3W4bxxV+lcG0FzawIik76AXvEsAFXCSNEKfohSsII3Iob7LcZWZnhagGAf7UcQy5",
	"MFL0ohdt0uTGF0UBiuZGa1JcAXqCM6/QJynOmV1yV1xaSlpAELg/M+fn+853zuxT3gq6vcCXvg558ynv",
	"CSW6UktFVx+6XVfv4S28asuwpdyedgOfNzn8HSYwN0NI4AImsDAvYQkpxMw8h8QMYQEpM3+GBcRwATEs",
	"zQhSmDL6M6cwg4l5DjF3uIu7fRFJdcId7ouu5E3uoWHu8LD1RHaFNd4Rkad5817D4V3xpduNury528Ar",
	"18+uHK5Perje9bU8kor3+w7/uNMJ5dYovkfvzAv0EBKIGaRmxGBJ3k1gAZOiu8kWdwMyUe1v0cFGhYN9",
	"hysZ9gI/lJTzh76WyhfeA6UChTdaga+lr/Gn6PU8tyXQ9/pnIQbwlMsvRbfnSftmO98bdziQtIXDuzIM",
	"xRE+gtcIww7+Y3AJqfmacIIl4jZCQGsMvoMULs0AUjgzY3hrRpiW2Lww3zAzgAmc01I4hx8hrvF+Mepf",
	"KtnhTf6L+ppVdfs0rNuAKOBrGPwFlmZsRmZAKCzNK/OKkW8JnMEcJswMITYDmBKxJmTzd76I9JNAuX+U",
	"7Z+Vpai4QSlHP5AjGHtsRmaIzkxgijkzA0jgHCbmK0jMK0pVTC/PYJInagYxvDVDMyJ3RxDb0jCn8JZR",
	"DcwxSqqDc5jAG0gRApjiffZ+5hI5/3/J7bcUwpj+j2Bqg2KQwAISwh2mWQzLknsVEUNSo4LKjKJPK5Je",
	"ryoi05LKZmBGuTJQNpBva3CTGnd4TwU9qbRrK8ACVKU3tGqZJRPmkMKstJdDlUvkTaiuB00WeoE+6ESe",
	"57B2EB168uAwCD53/SPHPmoJvyU9T7az61ALpfFKeEqK9knxBdc/Fp7bPkAP0e8Vq/jKCl+VeKiV6x9x",
	"gkQL1wsrYvoHxFRmryjHRbLEDGU1CzglTcWUxnBhH84QR1KoBC8WyNIZvTyBC0hQW80Qc2KeYfmkZCaX",
	"ubeUJ8zgAkWPxDlmdzpB5LeJeiG7ev2ru82NdDqMRH9kxivJn1jLKfLLjOGS3MXfL3O/HuzWH9xzmHlO",
	"/Dozp1Y/5iglGLV5ya7+Bd/DFJ8iprhFk/2Wkc2hGV0tWL3ylY8yy7jb1YLBGcRwnokUvoe/LOvmRP8J",
	"y8p8k3TiWLieQHoo6WvhHRwGQrXDyo6BxMPg56SipJRzgm9pTs2zgk+MCmvVHBGIUgTsTg7dEmLzDKa0",
	"yxwhfde2d0vcq+h6TiGcUAp9izCyVN/osSXOBaR5Vy8V4CqgVT2wuo0lxjZqvrYExIgzg+VY7lV28OxW",
	"cPiZbGmMbiXWG1G9tgqDooZxFevGStD1UsCOD2fFIOJyZZdZZ5HIk0V3F+YlxmUxHNU2BYA6/BeRq7BT",
	"Pbbyto5hvyK+h36oVdTSldr6N1hSfQ3MGEsRWe4wCnhmxuaFLW9LnzdmDAuYm/Em39125dazTA0S8ydI",
	"MvqlZoANY8MqdmKHdwLVFRobauS2q9TPzkgVti6QBlv3LSCAyj9A1tyYW/KADL47rR+6of4km7oqfPsu",
	"k7ABNTEU06x/D+GSZhCs7UrXccS9g6/R2ikxEGk2z8WQ8oqUod0d9sGjnUZj924FQFp2q+r238WR2pyu",
	"fcJBaZtPuP1qw3cNEgXmrQtPKCVObN3pG0eRPXHk+tREPsK3NxAiL7KtqkC6tr5qDrCdb0bgZL3ychMx",
	"SLEQCsP7Zo7tMWPTxD+pgVDHY6VtvzKnZb1qVIlvdhz42YcN27my2Whlq9KUDrTwKix9m0ncDcexkoH3",
	"qtW3iF5+LlsdeKz9TRxxTJStSLn65BESw+b7UAolFQ6566tf5/rxm99/yjfG1x9WEymdAYZ03sQ5L8f1",
	"m3xEJwZgfGzv40efsjpO9/VjqdzOyQ7Na6Vpfb3u5jm8yT4gT9kfokbjfksHn0ufftIYQbzH0G04a4l6",
	"onXPjuSu3wkq2VChEltFBYfRncD3Tu5WSwlloHK9GdcYvIZJPpUVpj6SjRSDZ+/vPbx2zrKJseKS2MaP",
	"t+EyI6gdN9/slJuNZa12dd49KxbMYWHGcEY2/zP4K1urDkrDsVShTdFurVFrUEX1pC96Lm/y+7VG7T4W",
	"stBPiFN1t7C4+ZQfbam8Wwj3T84ru5PLN/skh4dVqT+mBIWH+PSwzZscO1A57OKnl8fVGrt+pV74NNN3",
	"bny7+A2kv3/ti8O9RuMWJ+jbHUS3tNiqk+ltIEHs32vsbrO6CqNe+hxAtrLPLzctLH9uId2Kul2hTn5q",
	"hSLpxRFix4u47veLWkjIFlXw8T7CEUp1nONeztKeCtpRCy+oULJSm9EpjIbpHcwf+fJj3la4wyPlZQoU",
	"Nut10XNrYdRredFhLVP7+vEu8aZs7ZHG5ntEpvDYRIemlOZfmpNvMhTa9TvbDO6vcvQ/ieH6w1sx0/39",
	"/n8DAAD//x0f3N/OFAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
