// Package bookingsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package bookingsapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for BookingStatus.
const (
	BookingStatusActive     BookingStatus = "active"
	BookingStatusCancelled  BookingStatus = "cancelled"
	BookingStatusLateCancel BookingStatus = "late_cancel"
)

// Defines values for RouteType.
const (
	Experienced RouteType = "experienced"
	Novice      RouteType = "novice"
)

// Defines values for SlotStatus.
const (
	SlotStatusCancelled SlotStatus = "cancelled"
	SlotStatusScheduled SlotStatus = "scheduled"
)

// Defines values for BookingStatusParam.
const (
	BookingStatusParamActive     BookingStatusParam = "active"
	BookingStatusParamCancelled  BookingStatusParam = "cancelled"
	BookingStatusParamLateCancel BookingStatusParam = "late_cancel"
)

// Defines values for ListBookingsParamsStatus.
const (
	ListBookingsParamsStatusActive     ListBookingsParamsStatus = "active"
	ListBookingsParamsStatusCancelled  ListBookingsParamsStatus = "cancelled"
	ListBookingsParamsStatusLateCancel ListBookingsParamsStatus = "late_cancel"
)

// Booking Полные данные брони для экрана деталей (SCR-006).
type Booking struct {
	// CancelledAt Дата и время отмены, если бронь была отменена.
	CancelledAt *time.Time `json:"cancelled_at"`

	// ClientId Идентификатор клиента, оформившего бронь.
	ClientId openapi_types.UUID `json:"client_id"`

	// CreatedAt Дата и время создания брони.
	CreatedAt time.Time `json:"created_at"`

	// Id Идентификатор брони.
	Id openapi_types.UUID `json:"id"`

	// PriceTotal Производное поле в рублях (валюта RUB) = price·seats_count + rental_price·rental_count.
	PriceTotal *int `json:"price_total,omitempty"`

	// RentalCount Число прокатных досок (0..seats_count).
	RentalCount int `json:"rental_count"`

	// SeatsCount Число забронированных мест.
	SeatsCount int `json:"seats_count"`

	// Slot Полная карточка слота (конкретный сеанс прогулки на дату/время). Доступен только для чтения. Статус «Прошедшая» — производное значение по полю start_at, отдельным статусом не хранится. Итоговая цена брони производная = price·seats_count + rental_price·rental_count.
	Slot *Slot `json:"slot,omitempty"`

	// SlotId Идентификатор слота, на который оформлена бронь.
	SlotId openapi_types.UUID `json:"slot_id"`

	// Status Статус брони. late_cancel — поздняя отмена (менее 2 часов до начала): место и доска НЕ освобождаются.
	Status BookingStatus `json:"status"`
}

// BookingListResponse Постраничный список броней (SCR-005).
type BookingListResponse struct {
	// Items Элементы списка броней.
	Items []BookingSummary `json:"items"`

	// Meta Метаданные постраничной выдачи.
	Meta PaginationMeta `json:"meta"`
}

// BookingStatus Статус брони. late_cancel — поздняя отмена (менее 2 часов до начала): место и доска НЕ освобождаются.
type BookingStatus string

// BookingSummary Урезанное представление брони для списка (SCR-005).
type BookingSummary struct {
	// CancelledAt Дата и время отмены, если бронь была отменена.
	CancelledAt *time.Time `json:"cancelled_at"`

	// CreatedAt Дата и время создания брони.
	CreatedAt time.Time `json:"created_at"`

	// Id Идентификатор брони.
	Id openapi_types.UUID `json:"id"`

	// PriceTotal Производное поле в рублях (валюта RUB) = price·seats_count + rental_price·rental_count.
	PriceTotal *int `json:"price_total,omitempty"`

	// RentalCount Число прокатных досок (0..seats_count).
	RentalCount int `json:"rental_count"`

	// SeatsCount Число забронированных мест.
	SeatsCount int `json:"seats_count"`

	// Slot Урезанное представление слота для списка (SCR-002).
	Slot *SlotSummary `json:"slot,omitempty"`

	// SlotId Идентификатор слота, на который оформлена бронь.
	SlotId openapi_types.UUID `json:"slot_id"`

	// Status Статус брони. late_cancel — поздняя отмена (менее 2 часов до начала): место и доска НЕ освобождаются.
	Status BookingStatus `json:"status"`
}

// CreateBookingRequest Запрос на создание брони.
type CreateBookingRequest struct {
	// RentalCount Число прокатных досок. Не больше seats_count.
	RentalCount int `json:"rental_count"`

	// SeatsCount Число мест.
	SeatsCount int `json:"seats_count"`

	// SlotId Идентификатор слота.
	SlotId openapi_types.UUID `json:"slot_id"`
}

// Error Стандартное тело ошибки.
type Error struct {
	// Code Машинный код ошибки, например: slot_full, double_booking, slot_cancelled, slot_started, already_cancelled, invalid_code.
	Code string `json:"code"`

	// Details Необязательные машиночитаемые детали для динамических сообщений на клиенте (foundations §6): например, актуальная доступность для E1/E2, чтобы показать «Свободно: N мест» / «Свободно: M досок» без разбора текста message.
	Details *struct {
		// AvailableRentalBoards Сколько прокатных досок реально свободно (для нехватки прокатных досок).
		AvailableRentalBoards *int `json:"available_rental_boards,omitempty"`

		// AvailableSeats Сколько мест реально свободно на момент ошибки (для slot_full / превышения мест).
		AvailableSeats *int `json:"available_seats,omitempty"`
	} `json:"details,omitempty"`

	// Message Человекочитаемое сообщение об ошибке.
	Message string `json:"message"`
}

// Geometry Геометрия маршрута для отрисовки линии на карте Яндекс.
type Geometry struct {
	union json.RawMessage
}

// Geometry0 Массив координат точек маршрута.
type Geometry0 = [][]float32

// Geometry1 Закодированная полилиния (encoded polyline).
type Geometry1 = string

// Instructor Инструктор, ведущий прогулку.
type Instructor struct {
	// Id Идентификатор инструктора.
	Id openapi_types.UUID `json:"id"`

	// Name Имя инструктора.
	Name string `json:"name"`
}

// PaginationMeta Метаданные постраничной выдачи.
type PaginationMeta struct {
	// Limit Размер страницы.
	Limit int `json:"limit"`

	// Offset Смещение от начала выборки.
	Offset int `json:"offset"`

	// Total Общее число элементов.
	Total int `json:"total"`
}

// Route Маршрут прогулки. Справочник, доступен только для чтения.
type Route struct {
	// CapacityCap Потолок числа мест на маршруте. Новичковый — не более 8, опытный — не более 12.
	CapacityCap int `json:"capacity_cap"`

	// DurationMin Продолжительность прогулки в минутах (обычно 90-120).
	DurationMin int `json:"duration_min"`

	// Geometry Геометрия маршрута для отрисовки линии на карте Яндекс.
	Geometry *Geometry `json:"geometry,omitempty"`

	// Id Идентификатор маршрута.
	Id openapi_types.UUID `json:"id"`

	// Name Название маршрута.
	Name string `json:"name"`

	// Type Тип маршрута — новичковый (novice) или опытный (experienced).
	Type RouteType `json:"type"`
}

// RouteType Тип маршрута — новичковый (novice) или опытный (experienced).
type RouteType string

// Slot Полная карточка слота (конкретный сеанс прогулки на дату/время). Доступен только для чтения. Статус «Прошедшая» — производное значение по полю start_at, отдельным статусом не хранится. Итоговая цена брони производная = price·seats_count + rental_price·rental_count.
type Slot struct {
	// FreeRentalBoards Число свободных прокатных досок из общего фонда (12).
	FreeRentalBoards int `json:"free_rental_boards"`

	// FreeSeats Число свободных мест. Расчётное значение.
	FreeSeats int `json:"free_seats"`

	// Id Идентификатор слота.
	Id openapi_types.UUID `json:"id"`

	// Instructor Инструктор, ведущий прогулку.
	Instructor Instructor `json:"instructor"`

	// MeetingPoint Адрес или ориентир места встречи.
	MeetingPoint string `json:"meeting_point"`

	// MeetingPointLat Широта места встречи.
	MeetingPointLat float32 `json:"meeting_point_lat"`

	// MeetingPointLng Долгота места встречи.
	MeetingPointLng float32 `json:"meeting_point_lng"`

	// Price Цена за одно место, в рублях (целое число, валюта RUB).
	Price int `json:"price"`

	// RentalPrice Тариф проката за одну доску, в рублях (целое число, валюта RUB).
	RentalPrice int `json:"rental_price"`

	// Route Маршрут прогулки. Справочник, доступен только для чтения.
	Route Route `json:"route"`

	// StartAt Дата и время начала прогулки.
	StartAt time.Time `json:"start_at"`

	// Status Статус слота.
	Status SlotStatus `json:"status"`

	// TotalSeats Общее число мест в слоте.
	TotalSeats int `json:"total_seats"`
}

// SlotStatus Статус слота.
type SlotStatus string

// SlotSummary Урезанное представление слота для списка (SCR-002).
type SlotSummary struct {
	// FreeRentalBoards Число свободных прокатных досок из общего фонда (12).
	FreeRentalBoards int `json:"free_rental_boards"`

	// FreeSeats Число свободных мест. Расчётное значение.
	FreeSeats int `json:"free_seats"`

	// Id Идентификатор слота.
	Id openapi_types.UUID `json:"id"`

	// Instructor Инструктор, ведущий прогулку.
	Instructor Instructor `json:"instructor"`

	// Price Цена за одно место, в рублях (целое число, валюта RUB).
	Price int `json:"price"`

	// RentalPrice Тариф проката за одну доску, в рублях (целое число, валюта RUB).
	RentalPrice int `json:"rental_price"`

	// Route Маршрут прогулки. Справочник, доступен только для чтения.
	Route Route `json:"route"`

	// StartAt Дата и время начала прогулки.
	StartAt time.Time `json:"start_at"`

	// Status Статус слота.
	Status SlotStatus `json:"status"`

	// TotalSeats Общее число мест в слоте.
	TotalSeats int `json:"total_seats"`
}

// BookingIdParam defines model for BookingIdParam.
type BookingIdParam = openapi_types.UUID

// BookingStatusParam defines model for BookingStatusParam.
type BookingStatusParam string

// LimitParam defines model for LimitParam.
type LimitParam = int

// OffsetParam defines model for OffsetParam.
type OffsetParam = int

// BadRequest Стандартное тело ошибки.
type BadRequest = Error

// Conflict Стандартное тело ошибки.
type Conflict = Error

// Forbidden Стандартное тело ошибки.
type Forbidden = Error

// Gone Стандартное тело ошибки.
type Gone = Error

// InternalError Стандартное тело ошибки.
type InternalError = Error

// NotFound Стандартное тело ошибки.
type NotFound = Error

// Unauthorized Стандартное тело ошибки.
type Unauthorized = Error

// UnprocessableEntity Стандартное тело ошибки.
type UnprocessableEntity = Error

// ListBookingsParams defines parameters for ListBookings.
type ListBookingsParams struct {
	// Status Фильтр броней по статусу
	Status *ListBookingsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit Максимальное число элементов в выдаче
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение от начала выдачи
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListBookingsParamsStatus defines parameters for ListBookings.
type ListBookingsParamsStatus string

// CreateBookingParams defines parameters for CreateBooking.
type CreateBookingParams struct {
	// IdempotencyKey Ключ идемпотентности для безопасного повтора при сетевом сбое (NFR-9).
	IdempotencyKey *openapi_types.UUID `json:"Idempotency-Key,omitempty"`
}

// CreateBookingJSONRequestBody defines body for CreateBooking for application/json ContentType.
type CreateBookingJSONRequestBody = CreateBookingRequest

// AsGeometry0 returns the union data inside the Geometry as a Geometry0
func (t Geometry) AsGeometry0() (Geometry0, error) {
	var body Geometry0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGeometry0 overwrites any union data inside the Geometry as the provided Geometry0
func (t *Geometry) FromGeometry0(v Geometry0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGeometry0 performs a merge with any union data inside the Geometry, using the provided Geometry0
func (t *Geometry) MergeGeometry0(v Geometry0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGeometry1 returns the union data inside the Geometry as a Geometry1
func (t Geometry) AsGeometry1() (Geometry1, error) {
	var body Geometry1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGeometry1 overwrites any union data inside the Geometry as the provided Geometry1
func (t *Geometry) FromGeometry1(v Geometry1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGeometry1 performs a merge with any union data inside the Geometry, using the provided Geometry1
func (t *Geometry) MergeGeometry1(v Geometry1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Geometry) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Geometry) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Мои брони
	// (GET /bookings)
	ListBookings(w http.ResponseWriter, r *http.Request, params ListBookingsParams)
	// Создать бронь
	// (POST /bookings)
	CreateBooking(w http.ResponseWriter, r *http.Request, params CreateBookingParams)
	// Детали брони
	// (GET /bookings/{bookingId})
	GetBooking(w http.ResponseWriter, r *http.Request, bookingId BookingIdParam)
	// Отменить бронь
	// (POST /bookings/{bookingId}/cancel)
	CancelBooking(w http.ResponseWriter, r *http.Request, bookingId BookingIdParam)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Мои брони
// (GET /bookings)
func (_ Unimplemented) ListBookings(w http.ResponseWriter, r *http.Request, params ListBookingsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать бронь
// (POST /bookings)
func (_ Unimplemented) CreateBooking(w http.ResponseWriter, r *http.Request, params CreateBookingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Детали брони
// (GET /bookings/{bookingId})
func (_ Unimplemented) GetBooking(w http.ResponseWriter, r *http.Request, bookingId BookingIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Отменить бронь
// (POST /bookings/{bookingId}/cancel)
func (_ Unimplemented) CancelBooking(w http.ResponseWriter, r *http.Request, bookingId BookingIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBookings operation middleware
func (siw *ServerInterfaceWrapper) ListBookings(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBookingsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBookings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBooking operation middleware
func (siw *ServerInterfaceWrapper) CreateBooking(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateBookingParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey openapi_types.UUID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBooking(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBooking operation middleware
func (siw *ServerInterfaceWrapper) GetBooking(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bookingId" -------------
	var bookingId BookingIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "bookingId", chi.URLParam(r, "bookingId"), &bookingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bookingId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBooking(w, r, bookingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelBooking operation middleware
func (siw *ServerInterfaceWrapper) CancelBooking(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bookingId" -------------
	var bookingId BookingIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "bookingId", chi.URLParam(r, "bookingId"), &bookingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bookingId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelBooking(w, r, bookingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bookings", wrapper.ListBookings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/bookings", wrapper.CreateBooking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bookings/{bookingId}", wrapper.GetBooking)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/bookings/{bookingId}/cancel", wrapper.CancelBooking)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc/28bR3b/Vwbb/iChK5KSnZzNQ35IgiRwm0sMK4f+4ArCihzJe0fuMsulEdUQIJKx",
	"ZUO5uM750KBNnDr9kgKHohSltWhSpAD/BTP/Qv6S4r2Z3Z1ZzoqUqrs2dwbuYi05O/PmzXuf93V4z6r4",
	"9YbvUS9sWuV7VsMJnDoNaYBP7/j+r11v60b1JnwMn1RpsxK4jdD1Patssa/ZEYvYmHfYgH/OBmzIerzD",
	"JnyXsAO+yyZszAb4b5/18O/Hlm258GrDCe9YtuU5dWqVrY14Icu2Avppyw1o1SqHQYvaVrNyh9YdWHzT",
	"D+pOaJWtVsuFkeF2A15uhoHrbVk7O3ZM8GrohK1mHtH/xgZsxL/gHZXMiL0k7JRNCG/zDuyCd3mbd2Ny",
	"P23RYDult4kLWCpx1GvVrfJty6mE7l1q2VbF8Sq0VqNAac0J6br4wFozEf6hW3fDPIK/YT025G02YCes",
	"B6SzMZuwiPA9NuBtNgKqf8NGLGIn8jQmrE/wf3yfHbEe32NRzk5qsLC2kSrddFq10CqvlGyr7nzm1mFj",
	"yyV4cj35lOzB9UK6RQPcxMebm02au4vnQB1/BBSyAYsIm/AOYWOkrsdGrKeSO8gh18clzPSqBJYMBO6A",
	"bDUbvtekQrqd6i36aYs2Q3iq+F5IPfzTaTRqbsUBwou/agL19yz6mVNv1KgYWUWZdarrgXzftuq02XS2",
	"4HP2LYtYn0V8l435Pmz0lPX4Luvh/jt8l+8Tdsx67BREj7dZr0DYd1JLIr4LkglvDUGP+C6L2JB34MRB",
	"MvkXMF2EHx+hTo35Pr8PEwpOCu6+LFg7Ko/+MqCbVtn6i2Kq7UXxbbP4XhD4kj2ZEzv3RsgCUIHPAxy0",
	"a5MmdcLmesVveSFhfdA0wo7YAIaxHjtG5euR5ULhCgG9ZAMSUC90avErB2yC2vqQRepci7jDd31vs+ZW",
	"LnaAzZofrm+2ajULdh46bg3FwrnruDVno0bXJSEbvhNUmyj06XdIilUu7WSOXkrxAfJpjIp6QoSSimMd",
	"C9FHlMFP2/wLGNBnE9zrUXyiwL8271zSSfb4Lu8CE2PtG7AxoDIeVQ9Bo0d+3H2KBPLOWRTF5yTOXWK+",
	"HHKEgjBhQ7IQyzM74F02xPUOF20YAhO/RHl9nAAwCHY8LbwpzEg8CHiH2MZ6yI/3/WDDrVapd6GD30ze",
	"1g7vqVSxLjtN5Trij/gTNi4Q9hWIO57eCZuwF8AlPEpx1vwRGo0veBvoHZJUO9kJYUfAfXbIJvB/UO0R",
	"HILg+qUc8Hdswk75Pu/AcchjEFuBxyHhe7zLXoBWapTh2h/4Hr24AqlmTmHmcyHxytEBGwmcL2o0i6Qy",
	"aLRGMOSIjRTByDoQl8KuHOoWhF1/K9mTQJkbXkgDz6mJ+S7CKVfOsE5xCo1TP4CoL8F/UPT5QzToKGmI",
	"EUMwD3i8uyhsXfZSSB6KJkGgORZacwxieSkM+oqNeRcwHpVuzB8LLXzIBuwARYy3Ubf76IEIGf7ID9/3",
	"W171QhzyAIvxbY05/yjVsIdLgxBE7ITvs5cEdbPNu3yXt6Vegu15KTzSS2HC/2rxX3pOK7zjB+7f04tx",
	"pKVOoDHlezwWkAQwwwg4vQQxBwBd/AGqCghO6itIsQESX6L9gcPrsEh4lGJfHQR0VMO+AMFD1FZQwCGL",
	"yNuSJCT+Upj8DLfQxf92WF9sKrEF48QFAZpU8gw7ZgPJ+UbgV4BdGzX6nhe64fbF4a0ZOkGYB26IqVEc",
	"MuwKxxvMug12Qfhp8iymsW58SdD/zLRQH9FAGCrwrzC0YQfIKzDw7SUh2SADbMS7senPOG+x45K/0wJ6",
	"/pJKJWY0BADfoSRJVzI1QpEC9TH489+wofSg0JpF0luCKG1h9d1bS6XSm4sFy7Yagd+gQegKjz7B7XUn",
	"NBDwFD2VHhqhPorUieZc8H0bULUtRE9xTA74vghQUj9E+iJ2GpRWnZAuhW4dYj+vVUM3MY5hMwGfbVVq",
	"LvXCdbd6vqBacxxAyPjnqAIngE/o3aF/kZCuEWiOmm2rElAnPB/P0Mc7loc40Kx1Lk+m1j3v5s1L5O2q",
	"EbgVuh76oVMzySLOBdrQFx4uBtRoREfwR5+gx3YA0sjvkwUh7PxL5MWtX76zSN4iuMKrYzXA+as4eJHf",
	"qaEMUJ2AzBvXIJ4OqFP92KttZ8QkCVlhRDqBYRs/JAmAGc54qVDQgyeFlmUlzL9ydgxtW8osZ9MDtsPk",
	"wmWjG4WQlRxClo2E1PxwFmiuwhg59ry6lsRsoGcIQ0N8hKAcTKWieyOBBufVO5lEmrEHLaVliSRGnCC7",
	"beHM8fZUWNFPKiNIdprAUtVEg4I0TeVv/IpWkI+Slg/dZnhLZlLMOI9Gbleiw17sXLTZKcoHSKSWeJOQ",
	"/oYB0t2Q1puGRf5LzXfx/XTyoXIQMDlMmUwyD6Nb9boTbMN25f6dIHDwuU7DmXb6prPleuhZ/AJGT50X",
	"UiKnOoPFq4lsZCOXNDupIiJRMozClp9KhE589ySCJguJDYvICuF7rIeH0kfE0FJyi+VEU+GbQYwpyORv",
	"2e8wk5EkCl5g8u5L4ZOiZl88J5pyQp7HNCv+Fc3RcZJniQQIRuxIZlf6UjMHZh9DlZgzJPAn5FS8NuSv",
	"DfmfrCFXgPnPxp7/AWz4u/i1pEKpf+TkPiYiwdHLIIWGqNOYeTnSXgAbE+WWAP4Isn8pwn1xSZ1D7DLy",
	"M5fomMQiyW2a/A02Rsu+K+pQIjEZCQ6lOUGDGIhEiqmeiW+NpWMImsiOtLnsqWREmST1GptU/dZGja7L",
	"srFN9Ey0fJapG5s4NcDnbXWA6911am51HSjUTlerCk2puFImMtTKJuyAP8ZklJpVw4JBvOEJ1mw7SSox",
	"UrMbiWuCBbIxFtrAfY7QSRnw+0IJYZm4jPoywbI0MRCRBcykohfaJK9+eBPcuKncDhaVO7yblJR7YmU1",
	"Q5XUHAVd7y0X31uxCd/D/M8B3xeGdoiFPCx/kFe/Z8/VyhGblMlHiSK9GpGiccgvFLV/NQKVj9ixzG3D",
	"OPhLSN1QOHdEpuOmhS63fmeoSA8FssC/MwwvekxJ8T1THmMTshAf3ZhF/D5W1jpwaGdPO2W/pxFkquQ4",
	"axtxlW4WxUJwTtgkjqI0BUw2lOgDKcb+dZ/vx5VE2LFccDGLkoYOgSnYSZKqBhSOZN45Qkut6I2AoKwq",
	"iFqcuolI12xd6jIlTdXGiBJoYSbYIrylezDB6gfUr9PQGL78FhFDltJjTgLIPsRSbUdkPkcymMAhbZmH",
	"HxBUd9j1IAEAgc8RYf+NcI2aAnvwPfrxplW+bYThNraV9AUEg5ZJ5AH56SDXIwjWM4RpMXVm1n/KToQl",
	"cYKJ5qOkiYDvk9s1J7RJzdta06aTLPRa9Q2hAHXnsxviyxW0tulDNj7PPBt9GjQ1uh8rgE9EDIOYsfwx",
	"WaAenHCVNPzads316KJBJNawPtgMg1YlNBrQr9lYZEN4Fxs5Joi9fQxTu/yRwHCBEYe8y0ZsyLuGNMg5",
	"Q6zB9KpzuRNxo41hLQxrc+dV1Owb0VWAvV5nKxBSgAuadCeTSjH5EcJyarWE0+nsE5sAj5Xmomn+ijao",
	"6SX+BQ0QWkyiTfuA7+t4Z3Q0ZbvShZuhhOWTvlWylnGpvAD5mYTIGe1i2gJXzeitHl3cN5Y0ZIn1Ted4",
	"y2+FeW5gAioZHWCDAmHPkxrVBI9xwIY2meoXQPoT6ydzO3voK8iGgemMTsOpuCE4hI2c/GVHVj2HKdd6",
	"irWQplMFxQijlQkWVfcQZvro3MY9NWrfwzVRH8R+jXHuqOUV7VCumU692gpQQ9brrpebHTnCKV+o1V6l",
	"m0xnO2L1Ceo5Qj3mTNDXE5pErpeWlldKurG/bpTILcX2nRURJzbyAqkkg2G6KMJ9i6reT+Nbw9wKyj2T",
	"cIBmBLNqQ1GvZCO+b1pWfHA2K1BVPoGB+VApZ7J1Mc6IQq4efiKpyGz+ezZgp9MOiBTLaale8Py7boUu",
	"JoV6XZwX6GcNGrjUq2APTZoJFq8hJ5MBxuzvqswKmWvIwmTHPs8ESespgTNZQFrHWEWOErJ4G13iMW8b",
	"5F6WmjG5XkxTpIsFonaGzQc5RMvTv/q9UER0mo/4Q6D+1Uim6c35S72dM5L1e/RR+JcEI9t1cJ9wu0dK",
	"tHmiNTBj96FoJbqfmC6Rnifsa9zGoZBg2MGDTN4rjV5U+mDohXKmOghvBnR2hJamYkz9iGcGbEAzSQKE",
	"Q5jic9zUEYjH8oqOYD8zARiSmBd1nU1anDgi4EHwNt/jT5LkSfZw9XyyiZA/ZALJtlzNfT0LnhRHF2M3",
	"Grre1nrDd415tH9gR6JPKgUJzD/ERO+mtSV0dwSeRrGDpmDtPwsjhhYIJVXUd8ay44V3CfsdWGh2KIIO",
	"DGvFINOGNcLXa8ZyyX+KGEHQNheZb1wvXP/ZNYXfmzXfCdP1lYhGX9/YLPMUge7wXBRcKRVW3lyZhwLU",
	"UMOq/xEjwDEWpuJMQVICtKcLKogao8x9BIxw9DqL7i2/USqdUSXJI+97GVl8ruu+Ri8IgyxS8u5l0Xst",
	"h9zYs51p02V9AFF7/iKiFg9k/eO5y3Pz1SWwxCKLEtKbz8U+Y0yResd9peF9lgtrrH/EjIo5rGGUTpyG",
	"0rbJqsTSnpGuLH6ZYMGkqgk/TS6WwsSzS/c6RMfeEZxFtSXK42mpPM89uqTKuOI1nVEZX1l8bcL/9Ez4",
	"azvw2g78dO1ADq6f1zzk4jlWiiutwA23V4E7AvU2qBPQ4O1WeCd9ej8+gL/+208se1pc4651vDUhcu4D",
	"O01JPonb+DF5iY0rNz9e/YQUnVZ4p3iXBu7m9hKWKrWO/vS92b36ZfIOUkr+rlUqXamE/q+ph39iBQ0P",
	"Hy814qBUeu6EYUN0nbvepm8QgSfmWzqZVuXyVPuArbUD2pky6EC/8kXYDwjBmLBSJkYTJe5UvX3zRuZO",
	"irzDhQ+DpIcBPjlQChSHSyaFCt0wLhkZXhiyESAJrglBvGymAFm6S4Om4MxyoVQoYQ64QT2n4Vpl60qh",
	"VLgCcuuEd1CUihvxm+V71lZOojinZ1IWQ7uJbdQ5rnS0EfZbhL5TnGpXykdP9wkm/DEWI6KibPuIcxXg",
	"IsSXA7J1ZsxKNGt+WIhVtUD069XTN6pFqugBG4ibn8IRwTpVg4oE1o2qVbY+dJuhwlf1XvptM4ClQ4qG",
	"a+A79sy3lDvYc4xWLzvvrGWuFq+USnNcOZnv5oep6dZ8py1HUnTBAJG8WlrOWzXZRlG7wITLyXvWs17U",
	"r8shisaeqsW+YROlDxLveYcOKMBtKznuNfBM/Py2JNgmIMFYyfnF8n51saBdOV4uFK7Y+pVivYXurETY",
	"+dNcZPo6Drp0IrMat3fqoq51ZE3L+lR9FbyTPSLKqewEbUZHnq7M6yudJNhIgZeReryN3uthnEmM709J",
	"JBgI/OzI20N4a/kA/aOFj96/tXQdPSG8k3+HOlU0EvJS/o0qrTf8kHqV7aW/odvWeX6zYU3YfQraXt2+",
	"NKUxdrnt6F5GGLTozpTiLl+24hqV9UnSB6wZRqmdpdlKpvx4wUUV+mrp+uyXkhv28MLyHIThbWIYvLIy",
	"D0nTV/UuDWqex4wVfkPSzGmGnB07NcfFe8kPkuzkm+Z57rPxNsFgGy+Mx7euhXr2lMc03CtmazBFc809",
	"UXC9CDLQr8fpQPMBDXNRZj6LGv8SzB/D4Bn15qnqJaZG5OIqcGX2S+mPDeAbV2e/kdyEvjRZztn3uSS5",
	"KC9blO/lWddnyiURRYhjkSq+s7pUKl1ZxNK88LQjcPImsSeJdajH4vcjOqKiiHUrGcqKbIm4ZaLcJO2V",
	"yY+P/n2F75EfH3xFkryXuKYSZ72nG+mE1onbKBAuo7b3k99i+DKNjWLtWvy5jH7itdRLMwui/J4zjU34",
	"Q9H9gSmovuwRk8513BMC/ojwr8dsQmAV2TEiGi2T29pD+IjEPxHCH2M5TmO+4bKwGh2q3MvkijK+BW7u",
	"p671qbXMXpb5eXrVQ4Tx5C1FgmTdSTlmO44KRRk5woPSbvj8P4aS8xvs/3MbnAr1YD4rrORcUELVbMvt",
	"NZDAJg3umn3jm4FfbVXgQa2tH6H+Yb/qEuAH2tEXcebWsq1WUJOZjma5WHQabqHZalRqrY2CTFgV7y4b",
	"2glXQ2fL9bZwKfCaRRiNAIKtqLMWaor3l/IWXEsYNG/SJfXIE47urO38TwAAAP//J9Mi4ONNAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
