// Package slotsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package slotsapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for RouteType.
const (
	RouteTypeExperienced RouteType = "experienced"
	RouteTypeNovice      RouteType = "novice"
)

// Defines values for SlotStatus.
const (
	Cancelled SlotStatus = "cancelled"
	Scheduled SlotStatus = "scheduled"
)

// Defines values for ListSlotsParamsRouteType.
const (
	ListSlotsParamsRouteTypeExperienced ListSlotsParamsRouteType = "experienced"
	ListSlotsParamsRouteTypeNovice      ListSlotsParamsRouteType = "novice"
)

// Error Стандартное тело ошибки.
type Error struct {
	// Code Машинный код ошибки, например: slot_full, double_booking, slot_cancelled, slot_started, already_cancelled, invalid_code.
	Code string `json:"code"`

	// Details Необязательные машиночитаемые детали для динамических сообщений на клиенте (foundations §6): например, актуальная доступность для E1/E2, чтобы показать «Свободно: N мест» / «Свободно: M досок» без разбора текста message.
	Details *struct {
		// AvailableRentalBoards Сколько прокатных досок реально свободно (для нехватки прокатных досок).
		AvailableRentalBoards *int `json:"available_rental_boards,omitempty"`

		// AvailableSeats Сколько мест реально свободно на момент ошибки (для slot_full / превышения мест).
		AvailableSeats *int `json:"available_seats,omitempty"`
	} `json:"details,omitempty"`

	// Message Человекочитаемое сообщение об ошибке.
	Message string `json:"message"`
}

// Geometry Геометрия маршрута для отрисовки линии на карте Яндекс.
type Geometry struct {
	union json.RawMessage
}

// Geometry0 Массив координат точек маршрута.
type Geometry0 = [][]float32

// Geometry1 Закодированная полилиния (encoded polyline).
type Geometry1 = string

// Instructor Инструктор, ведущий прогулку.
type Instructor struct {
	// Id Идентификатор инструктора.
	Id openapi_types.UUID `json:"id"`

	// Name Имя инструктора.
	Name string `json:"name"`
}

// PaginationMeta Метаданные постраничной выдачи.
type PaginationMeta struct {
	// Limit Размер страницы.
	Limit int `json:"limit"`

	// Offset Смещение от начала выборки.
	Offset int `json:"offset"`

	// Total Общее число элементов.
	Total int `json:"total"`
}

// Route Маршрут прогулки. Справочник, доступен только для чтения.
type Route struct {
	// CapacityCap Потолок числа мест на маршруте. Новичковый — не более 8, опытный — не более 12.
	CapacityCap int `json:"capacity_cap"`

	// DurationMin Продолжительность прогулки в минутах (обычно 90-120).
	DurationMin int `json:"duration_min"`

	// Geometry Геометрия маршрута для отрисовки линии на карте Яндекс.
	Geometry *Geometry `json:"geometry,omitempty"`

	// Id Идентификатор маршрута.
	Id openapi_types.UUID `json:"id"`

	// Name Название маршрута.
	Name string `json:"name"`

	// Type Тип маршрута — новичковый (novice) или опытный (experienced).
	Type RouteType `json:"type"`
}

// RouteType Тип маршрута — новичковый (novice) или опытный (experienced).
type RouteType string

// Slot Полная карточка слота (конкретный сеанс прогулки на дату/время). Доступен только для чтения. Статус «Прошедшая» — производное значение по полю start_at, отдельным статусом не хранится. Итоговая цена брони производная = price·seats_count + rental_price·rental_count.
type Slot struct {
	// FreeRentalBoards Число свободных прокатных досок из общего фонда (12).
	FreeRentalBoards int `json:"free_rental_boards"`

	// FreeSeats Число свободных мест. Расчётное значение.
	FreeSeats int `json:"free_seats"`

	// Id Идентификатор слота.
	Id openapi_types.UUID `json:"id"`

	// Instructor Инструктор, ведущий прогулку.
	Instructor Instructor `json:"instructor"`

	// MeetingPoint Адрес или ориентир места встречи.
	MeetingPoint string `json:"meeting_point"`

	// MeetingPointLat Широта места встречи.
	MeetingPointLat float32 `json:"meeting_point_lat"`

	// MeetingPointLng Долгота места встречи.
	MeetingPointLng float32 `json:"meeting_point_lng"`

	// Price Цена за одно место, в рублях (целое число, валюта RUB).
	Price int `json:"price"`

	// RentalPrice Тариф проката за одну доску, в рублях (целое число, валюта RUB).
	RentalPrice int `json:"rental_price"`

	// Route Маршрут прогулки. Справочник, доступен только для чтения.
	Route Route `json:"route"`

	// StartAt Дата и время начала прогулки.
	StartAt time.Time `json:"start_at"`

	// Status Статус слота.
	Status SlotStatus `json:"status"`

	// TotalSeats Общее число мест в слоте.
	TotalSeats int `json:"total_seats"`
}

// SlotListResponse Постраничный список слотов (SCR-002).
type SlotListResponse struct {
	// Items Элементы списка слотов.
	Items []SlotSummary `json:"items"`

	// Meta Метаданные постраничной выдачи.
	Meta PaginationMeta `json:"meta"`
}

// SlotStatus Статус слота.
type SlotStatus string

// SlotSummary Урезанное представление слота для списка (SCR-002).
type SlotSummary struct {
	// FreeRentalBoards Число свободных прокатных досок из общего фонда (12).
	FreeRentalBoards int `json:"free_rental_boards"`

	// FreeSeats Число свободных мест. Расчётное значение.
	FreeSeats int `json:"free_seats"`

	// Id Идентификатор слота.
	Id openapi_types.UUID `json:"id"`

	// Instructor Инструктор, ведущий прогулку.
	Instructor Instructor `json:"instructor"`

	// Price Цена за одно место, в рублях (целое число, валюта RUB).
	Price int `json:"price"`

	// RentalPrice Тариф проката за одну доску, в рублях (целое число, валюта RUB).
	RentalPrice int `json:"rental_price"`

	// Route Маршрут прогулки. Справочник, доступен только для чтения.
	Route Route `json:"route"`

	// StartAt Дата и время начала прогулки.
	StartAt time.Time `json:"start_at"`

	// Status Статус слота.
	Status SlotStatus `json:"status"`

	// TotalSeats Общее число мест в слоте.
	TotalSeats int `json:"total_seats"`
}

// DateFromParam defines model for DateFromParam.
type DateFromParam = time.Time

// DateToParam defines model for DateToParam.
type DateToParam = time.Time

// InstructorIdParam defines model for InstructorIdParam.
type InstructorIdParam = []openapi_types.UUID

// LimitParam defines model for LimitParam.
type LimitParam = int

// OffsetParam defines model for OffsetParam.
type OffsetParam = int

// OnlyAvailableParam defines model for OnlyAvailableParam.
type OnlyAvailableParam = bool

// RouteTypeParam defines model for RouteTypeParam.
type RouteTypeParam = []string

// SlotIdParam defines model for SlotIdParam.
type SlotIdParam = openapi_types.UUID

// BadRequest Стандартное тело ошибки.
type BadRequest = Error

// InternalError Стандартное тело ошибки.
type InternalError = Error

// NotFound Стандартное тело ошибки.
type NotFound = Error

// Unauthorized Стандартное тело ошибки.
type Unauthorized = Error

// ListSlotsParams defines parameters for ListSlots.
type ListSlotsParams struct {
	// DateFrom Фильтр: слоты со стартом не раньше
	DateFrom *DateFromParam `form:"date_from,omitempty" json:"date_from,omitempty"`

	// DateTo Фильтр: слоты со стартом не позже
	DateTo *DateToParam `form:"date_to,omitempty" json:"date_to,omitempty"`

	// RouteType Тип маршрута (множественный выбор, OR внутри группы)
	RouteType *RouteTypeParam `form:"route_type,omitempty" json:"route_type,omitempty"`

	// InstructorId Идентификаторы инструкторов (множественный выбор, OR внутри группы)
	InstructorId *InstructorIdParam `form:"instructor_id,omitempty" json:"instructor_id,omitempty"`

	// OnlyAvailable Только слоты со свободными местами (free_seats > 0). По умолчанию false — показываются все.
	OnlyAvailable *OnlyAvailableParam `form:"only_available,omitempty" json:"only_available,omitempty"`

	// Limit Максимальное число элементов в выдаче
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение от начала выдачи
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListSlotsParamsRouteType defines parameters for ListSlots.
type ListSlotsParamsRouteType string

// AsGeometry0 returns the union data inside the Geometry as a Geometry0
func (t Geometry) AsGeometry0() (Geometry0, error) {
	var body Geometry0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGeometry0 overwrites any union data inside the Geometry as the provided Geometry0
func (t *Geometry) FromGeometry0(v Geometry0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGeometry0 performs a merge with any union data inside the Geometry, using the provided Geometry0
func (t *Geometry) MergeGeometry0(v Geometry0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGeometry1 returns the union data inside the Geometry as a Geometry1
func (t Geometry) AsGeometry1() (Geometry1, error) {
	var body Geometry1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGeometry1 overwrites any union data inside the Geometry as the provided Geometry1
func (t *Geometry) FromGeometry1(v Geometry1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGeometry1 performs a merge with any union data inside the Geometry, using the provided Geometry1
func (t *Geometry) MergeGeometry1(v Geometry1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Geometry) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Geometry) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Список слотов с фильтрами
	// (GET /slots)
	ListSlots(w http.ResponseWriter, r *http.Request, params ListSlotsParams)
	// Карточка слота
	// (GET /slots/{slotId})
	GetSlot(w http.ResponseWriter, r *http.Request, slotId SlotIdParam)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Список слотов с фильтрами
// (GET /slots)
func (_ Unimplemented) ListSlots(w http.ResponseWriter, r *http.Request, params ListSlotsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Карточка слота
// (GET /slots/{slotId})
func (_ Unimplemented) GetSlot(w http.ResponseWriter, r *http.Request, slotId SlotIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListSlots operation middleware
func (siw *ServerInterfaceWrapper) ListSlots(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSlotsParams

	// ------------- Optional query parameter "date_from" -------------

	err = runtime.BindQueryParameter("form", true, false, "date_from", r.URL.Query(), &params.DateFrom)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date_from", Err: err})
		return
	}

	// ------------- Optional query parameter "date_to" -------------

	err = runtime.BindQueryParameter("form", true, false, "date_to", r.URL.Query(), &params.DateTo)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date_to", Err: err})
		return
	}

	// ------------- Optional query parameter "route_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "route_type", r.URL.Query(), &params.RouteType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "route_type", Err: err})
		return
	}

	// ------------- Optional query parameter "instructor_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "instructor_id", r.URL.Query(), &params.InstructorId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instructor_id", Err: err})
		return
	}

	// ------------- Optional query parameter "only_available" -------------

	err = runtime.BindQueryParameter("form", true, false, "only_available", r.URL.Query(), &params.OnlyAvailable)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "only_available", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSlots(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSlot operation middleware
func (siw *ServerInterfaceWrapper) GetSlot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slotId" -------------
	var slotId SlotIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "slotId", chi.URLParam(r, "slotId"), &slotId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slotId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSlot(w, r, slotId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/slots", wrapper.ListSlots)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/slots/{slotId}", wrapper.GetSlot)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa727bVrJ/lQPe+8HGpSXZSdtEQD8k97ZFLtomiFPcD7mGQEvHDluKVEkqiDcwYMlJ",
	"k8DZeNvNYotu/2y6i80CxWJl2app2ZKBPMGcV+iTLGbOIUVSR5btzS5QoEARlDJ5zsycmd/8Zs7cN6pe",
	"veG53A0Do3zfaFi+Vech9+npf6yQv+t79Rv4K/5Q40HVtxuh7blG2YA/QwSH4qloi40yEy04hKFoiy38",
	"3yETLdGGjtgQbRjCEYMB9JjYgA4MxFPxGHqGadi4yqdN7q8ZpuFadW6UjZoV8sqK79UN0wiqd3jdwo1X",
	"PL9uherPc6Fd54ZphGsN/CIIfdtdNdbXTRL4lvfaxIVjGMI+/HiysKF3HlGvuUHoN6uh51+rTRL4S9iD",
	"HgxEGyLxACLoQwfFExtii0EEA5RZbIhN6MufYQhdNgNHMIAhSk06dXEJGIgtOGDQFVuwg6+a7PpNBl0Y",
	"iE1cAyIGu7TUMRyLrVnDNPi9huPVuFEO/SbXq28nOlTsWsYIdsjrQcYazSa9kjNE8oPl+9YaPgfhmoM/",
	"4If4/L5dt8NJBvoaOtAXLYjgCDp4tqR5j4lHEMkDZuLXcAg9OFKGRAvRf2IL9qAjHk08Wwc3zihV4ytW",
	"0wmN8kLJNOrWPbverBvl+RI+2a56SjSy3ZCvcp8O+/rKSsAnavECpRNP6JwidLuhaKMDonQdOIROWtxo",
	"grgebaGXNy1gSS+g66xduWvZjrXs8Elyfg9DsnGfwiUfPtCFIfoW7JGzHaFLHSkf7NDjzIrPeSXgVhiw",
	"/2+WShc4K80WGHyH32/CES2PKg8gEs/YiuUEnP208VzGYR86sC+2oAsd8Uy0RUtso11a0CtMMonrrFWs",
	"WCu9aWiTxCTLnudwyyWT3PSaIb+11jjBHBEco46IGo8xeFDTf2f8+ShihWTXBh938cRvG653165yuSb3",
	"be5Wec1YOkcwLjpeeA64SrwFOvFRNazwzkiRgNY1TMPnnzZtn9dirTWwqgcSPDGfBw3PDTjpftWq3eSf",
	"NnkQ4lPVc0Pu0v9ajYZjVy0UuvhxgJLfN/g9q95ATfHNGnmCVav46nvTqPMgsFbxd/gGenikYoOOlHJE",
	"h9Ia+npbQvM+dOAY4Vi0oIMOLqEZv8L0g1/1CcY3oEfYPcBXRVs8xeV69PMexcFAbImHuKBEA4kQBwU6",
	"m8Q0/+nzFaNs/EdxlMuL8q9B8R3f93xpntxpnVkRNoNS0HNEL22YjIK5UvWabkjejOvsQYSvYbjCED9h",
	"84XCBUxYhxAxn7uh5cSf7EhIQT6QXmuWNLzmhtx3LUfqcJ5TtNUKFU5LZA7yJfrmHP5D+CIeU7qQNAUR",
	"qy+RSeoPO2ITDuTR9cQT8bmkMvspivBaDuWLBBAkaGwjyKFsEexgPGEk4ZF1Kb91aM8PvfBdr+nWzmUh",
	"1wsrK/R1xji/Vwfdoa270MEUShCGoomW2BQboqVYEnrFgYz912KEf2rzj1yrGd7xfPtX/HwWaaYXyBjl",
	"ezoW9IRenH860FXUK8JgEZ9BJLbJcUZRrNwGRTxQGSHCnyRfkXq1KcH1YEDkBMNuFyODUKMPPXZFiUTC",
	"vxYjf0sqbNK/behKpeIgRdMqcECZ0uJpNIaoQBlTbYoyJSGbpzoUWgPiMhsS+GS89WT0jVw9wqze8L0G",
	"90NbQro8IB0JpK+SJNtHEpJZy2R56CozzDmVlabjmKzmNZcdXln2vE9sd9WUf6pabpU7Dq+p5yC0/BCf",
	"LMfnVm0t/YLt3rUcu1ZBCQuUZ5VXGckuOu5b46FlO4FGJwRnBJ1tsnHaWXqScUiFh0R020mESDejH+gY",
	"9+AQvXSPXiYShklEtNAm4iExN9om5p4HZCe04CEyUcrlPTZDAEGuF7BXL9+cLbPxTEBMvC02Ex7ekTvL",
	"xIa8JpXkpFzvzBffWTCZeET+tYMJJyF6qLV4yl79AC/SxBKGZfZhwitfHbKi9pUP1M642qtDTDM92FeQ",
	"LfkXQmmbsi/xU6bCfNzpEv5YUZlr2bP8WqCl8f0UQVZ5Q3IglcYTmQjIRhVLjj3DkM3ERzeAnnhInLeN",
	"h3bysrMZ39OUImZKHUq309VQpp4qsXQc5PCq1MoEYKJQEg+sKHXpISfG/E+sfzvZMKvLgrZqUT95yx/z",
	"aojaJWA9ptVLiTDExvvZuJEQlA8FLMNgJ61ELxvZWa+TJxEbK8Nr6AzbBW0XYMR3b0t4G+mwpNHvPe7V",
	"eeivaRT8LSGG4m6xJbOVSexTQ/VKS6WXiFG4o9ZRAgASn3sM/k5wTZGCOnguv75ilG9rYbhFtXhXQjBG",
	"mUIe9J82Wb0H/THBqH6La5bcql/lF6JqGLlmhFIp1iq22G3HCk3muKtLmeWUCd1mfVkGQN26d03+cYGq",
	"4tFDvvjJPd/X0RRKNRApfk+MXQLfMaXvKDas2GYz3MUTrrGG56w5tstnNS6xlOkMaWussa6Pycir98Sm",
	"eCIxXGLErtiEQ+iLzXFQs2tnKt+0vSY6tqntHVngafY6QitNXDcVZl9TWRKJ7akBRBLQhrrYuWGt2i4l",
	"sQ94aGl5hMycSeWlOoBSQtWWeESU5SDTkRm3r+wdjW/xR0pAlDFZZtnPxFYW70o68FY9nnN3kGTmU9wq",
	"2Uu7VeiFlqPZ6VsFkVN6bJkNLurRO310cbMt6WLJ/XXnSH2ZCTQwAZVcDEBUYPBCFhWI2nSMEfTNLENJ",
	"uG6S/SRiEkNRCUpDS62GVbVDJIQNjVzfUeNDkvn+yGqdVLZQqTMNir0Cg28IVNDnEGa6RG6pHUaFD6UY",
	"OolLJqM6dUtSgglvzS9kDuWS7tRrTZ8ipFK3XZ0qZNM9WvLHdBGTal9kzU5YfURxTlAvHrIZyfVkJLHL",
	"pbn5hVI22V/WeuRqKvedVPIkOXLdPDPOaRLTeRHuGwp1mROimLXn1k6h3LcKDiiNMDRcnz5FxrU1uW9+",
	"simSFuYJUKlWMrNunHOFiXF4S0lxutaocstxr56RHcrZpP7MuvNMqm8pXeWsjc1Fxwv1sQmHccqOOc+Q",
	"ROukmpZshmQdQJ8aELFYokWUeCBaGr8fSMKFZcxmEbrEdI/E9myBwfOzQg6TdTN+IlpY8FAgEmneE49R",
	"+leHqlFOYkTkeYqZo+9l+4cyrSmOIp4xqmwrSJ9I3b1UtXkU34vR1qmLvIdJ6qJOSIHBl6TGrvRg1OAz",
	"2q7DYIeEGoyql7R8+OrbrOHbVf5qP91O/K+4Vaj+lm4cjoMwXS1Mq9BejjJWa5y8n1iwocwsKRB2cYkH",
	"pNQeusf8QhbB3tIB2Oj248yiqUxRYMggREs8Ep8nzZP84WYEeUMnyBlRcRQHp8JDO0NfT4KnFNGl2o2H",
	"trtaaXi2q4vV38CebP+NQIL6D7HQG6nrJroYkm3UmKClsPYPMolRBiJPlVdUA9m9Y2KTwe8wQ8OuLDqo",
	"rJUv6RTOCF5xLJ3wf5U1gpTtVGK+cblw+a1LKXuvOJ4VjvZPVTTZ/d1Vzf7PCeh2zyTBhVJh4c2F00hA",
	"EarZ9S8xAuzjP0mnIN59iJULI/K/g6CH5IBQ4zB3iUsVDmbCZyTzzY+u5roDb5S0lCENINosJSuLB9nY",
	"z8iLziBRoC82X5e8lyaIGzPbqTld3s1J1NaettID+VeceXL1QJ4fp0P7hMkF2jdsBtPExIS7KN+Mq4mJ",
	"2KetKUbsuDtCoN40CqujOYmhYgtnMCorXAalTV1Wib095115/NLBgi5UE3vqKBYa8X07CG+qi80J1UWu",
	"Po25ybFq8fRH9qP5kMX/vjlXKsmMlWsLTGjC/C1d3skbf7l4hiapsi9ZZKp7NOt1y9e1Woy6qtBPWiJX",
	"z48dPYmhlppk3MXEl3X3FIpvZfNfTD1RjFrToTui5CZgIveMdR3f6U8Un/uqd0QJXbZF91Ra6pLxJW9L",
	"UdKYJ6aP4oSj/YUf/dz50S9J9pck+/NNshOS5llz78RkiTbj1aZvh2uLaB2Jesvc8rl/pRneGT29Gx/A",
	"//7fLcPUzbjJm26atJAXGpE56vd+Hl/9U2cYsZnduL54ixWtZnineJf79sraHN0DZ6YARt9Nv98vs6sk",
	"qRySq4beJ9yV83KFeM6LRpTopZH33AnDhrzqt90Vb1L7TrSommmngWtIEYfIqZJJJ76z8LlVm/NcZy32",
	"5R70ZZk0yzA1PhiN1KohP6ryR7UTzQf04KDA4CVBM3UJU/fLlLqob8Cu3LiWm29RE0j0oHoqJN2xamXL",
	"W6HdOV2ghXYY39NpPujDISIM7fnTxnOGoYQOdpf7gTTXfKFUKFHXvcFdq2EbZeNCoVS4gM5shXfIv4oB",
	"fVa+b6xq+/Jf0HBQl2z7BDpyxCKd3odimy5teumBypnxs4hpQazjEPpnPICEHJjs6uJcqTQ/Sy3xeE+0",
	"weTDnjykmZ2xfFvObM5MGdiUEN8uiEeF+G4+QSIUhBpq8W0muccBe/UDXdCofnmPLv81wwpSqyE18uJr",
	"uT5BMQyTRpfqfyGN2Je2VmMpkXhGd5wNLpuf12pG2UAGHrtHej7+th6cR68Us/Pz6+apPojn10/xem5E",
	"9RRfjE+dn+IjzXDwKb5KDW6fZo/UhPT6Um6Wc6FUOsUo1+kmosZqKt1w1IsJxRPCwUUpjG6PROhiavqU",
	"Ppmf/klmcI1EUiPK0z7MjklSJoyrjcma6MEDYdNaRd82pMcv4XIS5Yr35ZTu+mS4U+30eBBpdI06Xrfk",
	"uu1RDE8XZsu5ewOUNL77MVO8Nte6ItDoj08LoFqmakaLLXPiSFLChKbM2Izjw3uc4OHM6JAepv6Xu7zW",
	"zZ9rj+jcHnuxdHH6R8m06mtz8a8m3tvo3DlFFOmQ0hTx9hKeQ8D9u/ERZg12w/dqzSo+pG9b9mj0jSaY",
	"5tBDqHb5MS43DdNo+o6iZ0G5WLQadiFoNqpOc7mgWHbx7rxmwGQxtFZtd1VmxHbs9pS1aDhp2kaB/H5u",
	"0oZLiXU08wSKFxR1VMQcMYXRCL808PrS+j8CAAD//+0wVxJTNgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
