// Package authapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package authapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Client Клиент сервиса. Аутентифицируется по номеру телефона (логин в формате E.164). Сразу после регистрации (verify-code, is_new=true) name ещё не задан — пустое/отсутствующее имя означает незавершённую регистрацию (дозаполняется через PATCH /profile).
type Client struct {
	// CreatedAt Дата и время регистрации клиента.
	CreatedAt time.Time `json:"created_at"`

	// Id Идентификатор клиента.
	Id openapi_types.UUID `json:"id"`

	// Name Имя клиента. Отсутствует у только что зарегистрированного клиента до шага 3 (PATCH /profile).
	Name *string `json:"name,omitempty"`

	// Phone Номер телефона в формате E.164. Используется как логин.
	Phone string `json:"phone"`
}

// Error Стандартное тело ошибки.
type Error struct {
	// Code Машинный код ошибки, например: slot_full, double_booking, slot_cancelled, slot_started, already_cancelled, invalid_code.
	Code string `json:"code"`

	// Details Необязательные машиночитаемые детали для динамических сообщений на клиенте (foundations §6): например, актуальная доступность для E1/E2, чтобы показать «Свободно: N мест» / «Свободно: M досок» без разбора текста message.
	Details *struct {
		// AvailableRentalBoards Сколько прокатных досок реально свободно (для нехватки прокатных досок).
		AvailableRentalBoards *int `json:"available_rental_boards,omitempty"`

		// AvailableSeats Сколько мест реально свободно на момент ошибки (для slot_full / превышения мест).
		AvailableSeats *int `json:"available_seats,omitempty"`
	} `json:"details,omitempty"`

	// Message Человекочитаемое сообщение об ошибке.
	Message string `json:"message"`
}

// RequestCodeRequest Запрос на отправку OTP-кода на номер телефона.
type RequestCodeRequest struct {
	// Phone Номер телефона в формате E.164.
	Phone string `json:"phone"`
}

// RequestCodeResponse Ответ на запрос OTP-кода. В демонстрационной backend-реализации code возвращается в ответе вместо отправки через SMS-провайдера.
type RequestCodeResponse struct {
	// Code OTP-код для демонстрационной реализации без SMS-провайдера. В production должен отправляться через провайдера и не возвращаться клиенту.
	Code *string `json:"code,omitempty"`

	// ResendAfterSeconds Через сколько секунд можно запросить повторную отправку.
	ResendAfterSeconds int `json:"resend_after_seconds"`

	// TtlSeconds Срок жизни кода в секундах.
	TtlSeconds int `json:"ttl_seconds"`
}

// VerifyCodeRequest Подтверждение OTP-кода и вход/регистрация. Только phone и code: на этом шаге ещё не известно, новый клиент или существующий, поэтому имя здесь не передаётся — для нового клиента оно дозаполняется отдельным шагом (PATCH /profile, шаг 3 SCR-001).
type VerifyCodeRequest struct {
	// Code OTP-код из SMS (4–6 цифр).
	Code string `json:"code"`

	// Phone Номер телефона в формате E.164.
	Phone string `json:"phone"`
}

// VerifyCodeResponse Ответ на подтверждение кода — сессия и данные клиента. Для нового клиента (is_new=true) поле client.name пустое/отсутствует: имя дозаполняется через PATCH /profile (шаг 3 SCR-001). Существующий клиент возвращается с заполненным именем.
type VerifyCodeResponse struct {
	// Client Клиент сервиса. Аутентифицируется по номеру телефона (логин в формате E.164). Сразу после регистрации (verify-code, is_new=true) name ещё не задан — пустое/отсутствующее имя означает незавершённую регистрацию (дозаполняется через PATCH /profile).
	Client Client `json:"client"`

	// IsNew true, если клиент только что зарегистрирован (имя ещё не задано).
	IsNew bool `json:"is_new"`

	// Token Bearer-токен сессии.
	Token string `json:"token"`
}

// BadRequest Стандартное тело ошибки.
type BadRequest = Error

// InternalError Стандартное тело ошибки.
type InternalError = Error

// TooManyRequests Стандартное тело ошибки.
type TooManyRequests = Error

// Unauthorized Стандартное тело ошибки.
type Unauthorized = Error

// RequestAuthCodeJSONRequestBody defines body for RequestAuthCode for application/json ContentType.
type RequestAuthCodeJSONRequestBody = RequestCodeRequest

// VerifyAuthCodeJSONRequestBody defines body for VerifyAuthCode for application/json ContentType.
type VerifyAuthCodeJSONRequestBody = VerifyCodeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Выход
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Запросить код подтверждения (OTP)
	// (POST /auth/request-code)
	RequestAuthCode(w http.ResponseWriter, r *http.Request)
	// Подтвердить код и войти/зарегистрироваться
	// (POST /auth/verify-code)
	VerifyAuthCode(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Выход
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Запросить код подтверждения (OTP)
// (POST /auth/request-code)
func (_ Unimplemented) RequestAuthCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Подтвердить код и войти/зарегистрироваться
// (POST /auth/verify-code)
func (_ Unimplemented) VerifyAuthCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestAuthCode operation middleware
func (siw *ServerInterfaceWrapper) RequestAuthCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestAuthCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyAuthCode operation middleware
func (siw *ServerInterfaceWrapper) VerifyAuthCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyAuthCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/request-code", wrapper.RequestAuthCode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/verify-code", wrapper.VerifyAuthCode)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xazW4b1xV+lYtpFhQyIilLdWAGXTiGi6aIayFS24WtCiNyJE1CzbAzQzeqQYA/dmzD",
	"jtWkARIETQKnCy+6GdEai/ohBfgJzn2FPElxzrnzRw7FRLULtBvDJGfuvefvO993ru5qVWen4dim7Xta",
	"5a7mml7DsT2TPrxn1D40/9w0PR8/VR3bN236r9Fo1K2q4VuOXfrIc2z8zvzE2GnUTX6yZmoVbcOorbvq",
	"fV3bMT3P2MLv4VsIoQ+hbMNQPoZQwBkEsg0BnEIou7ItHws4hADOZBtGsgNBUcD3+H9+Sz6RXXzrGEay",
	"LdsQwrHswhAflV35BJcL6esDCGCIe8j7uOAQAvkAQhjCAI6KWkvXvOq2uWPgkd9yzU2tov2ilLijxL96",
	"peuu67haq9XStZrpVV2rgYZfyBBRwFPQ5wE91NaFZxq+t151mrYvoA9DXOcABvgYBHAII3xFLBSLiwIG",
	"cAID4Zq2b9SjV/ZhBCfyiXwIYXqtObLwfds3Xduosw0XiaKlVlg3aYlMIJ/LLozm8R80fSQfwgn+F02Q",
	"XQjgGAMHI7Yf9mUPjjh0oXwkPxfkqkN6FQ7hJYSvJShfwFD20PsU6qHck3uCzjaAfTiGQMgOhawPA8ot",
	"3HPVcW4Y9q7Kdu9CjvIdZ33HsHejnPeyvnqGoZMPMWvhVMApJiy8QHelM2QEfeWzProV84Q9dkZufCy7",
	"cCx7r9tl2bPJBxBQKVFKp04nH4sf218K+hhCXz7GnIOhwLfhFE+Kju7S7wH04RgGYuXGyjyte4A2iQKu",
	"Jx+RVQE9nZTrPtkbCBjwD/hBduT9+GUqhJUbK3OTLsKyP4URvES3qgzEQwxVYbimZ9q1dWPTN911z6w6",
	"ds0TBdmB0yKfGcu4O16t6uAB19LvbaPpbzuu9VezdqEMaaYXyCTHD+wA2SPc6GDGBol55LNPYSD3yPAE",
	"3FQ1HUAIRxgxyukuhIgHBElHWIcjOOYw9dm+FwgYBKbHEIqr6kh0+NeSTd+RCT36twt9NirCLgyNwkw8",
	"U/p4ORbDoKi14iNRXV6rW8rpY9t+Q2kYwhBTJ1viAv6G5+EfYSDvwYD82U47/IwTZ8S4LHuCPQmhvKcw",
	"uEBuewEDdiZ+L9twCgGF4Xpx4fISpuYzxjVVprKDawiy9wWeh6BJWScKd0zX2tydxwzRheWt2+ZffuW7",
	"TXNO2MaOGSEldwUMHvW0qAx75OERhCXM4azT5VP5CEJ8bQCnBIFxCww4IBiJQypUtPeh/Jzgsief5h5W",
	"PhUFqkMqEUqhodyL3YedlV47FMtXV6/9RpQarrNp1c25oqZrDddpmK5vMa+ouqbhm7V1Iy+MX5I7GQX6",
	"tCKefor74DgJOkK5rm067g6uq9UM35z3rR1T0zV/t4Fl5vmuZW9hilu1nJ2/pkKKMwR7Befjeds0m1Yt",
	"bweMXu4eFIvsemJKyXAOUndHJBLyAbfaQ2IZaX8MFDsivhP1lcwmiBIjIR9S/QdiURRywhRDFh6UVkOY",
	"Mj75wLS3/G2tslAu69qOZcefcwxvbDt2nuXfRpU1WVdTaqko4GvZ4VyTT7CgkmI9RnYhknrMnv7td65c",
	"ubJwaXHpl5ffwewzfOQwWkX70+3bb99amL+ydvt27e6CvrDUemsyeC1dwxZuuQjztzSKL1ulp1N3LX7R",
	"2fjIrPpofEyzxhss0aEhVq9sM1lljhQyY0roySCnXKh7TKz5DwjoraFCem5WmbV0MU43K8KrO/76ZrNe",
	"10XNaW7UzfUNx/nYsrd0/qlq2FWzXjdr6rPnG66Pn4y6axq13fQDln3HqFu1dTxhNgLxLnm1UTN9w6p7",
	"uUkSElHcoxxPd7JQUHKwwSP5gBkEocNj1QPpC+oxB3CCSXJADwdETRCeOugTeV8Qz8JtHkVqgKlFpmJC",
	"Udh0mnaN+qInXj2/PFcRk+wd81B2ZQ+3xqNCwDuzGOnBWVqY8LmuL5SuX9JVNcM+ioQz6oIBWy2fiFf/",
	"gmfQx1+JgAxhVBG/E7RnR3ZfnYhS7iM31M642qsTlAaIx9yOYnpFbj0moAmE4iCTSWfcMay6gemh1MaG",
	"Y7i1vJg9o8SLMEpxfcZOJb3iMzGMR54aYSAyFlCHodANIZT3EYKQ8GJIz1s2i10JKKF02TJdTLnEHJJI",
	"s81Qrp55Yk6cUwY34h7pAowNiutBlCb4MxK7eMOsLZcmbWnlwE7MJCeses4Igz2e9HKqbhiCxkshRKKw",
	"nzYiHOsMmazjSETOymhRimG3OBNfCd4SG/JgVemya07NTA0kxkz9KqHuKioZLSJ74ubqcqRFAvXIcGpX",
	"miyJ19jZ3ly34kPOdCJPeXKM+S7RQmRAShBl/FcU8AUrD0ykYYaXjRQLORIbRvVj067NR1WUZvYCAy8o",
	"mQ6J6aEuDJIW308JM0ynfpRm3DCzMjNFP0lxnsWE6IhaQzsvoPmNNbEy1UjONzPXPIW+U4+DDmy4Tq1Z",
	"xY0JzuAEJT2qi7R9J3IPm8I4zc5bVCiFNeHWeIF0j5O9bCJyDo6nYO3ukn45L/Mw8SZVdT4IqTNTC04R",
	"2g61oh4yo4x+T8vwQTTUSwQ/q5Tx+s4Yc7mc1wZ8v37OOZ9xjxHwkgI5ZIGh4KKfOS0E8n5mv8VyORer",
	"07WZ3n2K8/IK9w8kEc8Hv+/xmKpa2vCSlQzBeRb0SFTRRKWUK/L2igJ+SEWI4ESoYmX+I+RnRFxOIzUR",
	"ZlUquq6vKnUII51Bth9x1ESkq4kACZ9H6oVIuA7gSGf5rDZDNa2E7CFleweTYsijsXgiIj9X6EECOeYS",
	"IyqHPFE04nybrmspyQ5SRDQ2Gz0wJqJ09ZtYFCvXPpwvlxfmLoI6A4YNUVj6sf33y4ICc0+25yar9WfU",
	"6v9Q99LZR7Nq4Sf3sLOpxREXBuYLDY06hDh7gmWEuj/gJ7OS/cuZyVXIjHNUboWiSgOsIo93zp/hoA2V",
	"OO8vMHwRhcmEFPAsv+DGqnNaY0Z6lTqGmrJjYbAqoq9Oc/I+HtydN1ZU472WrrH3JsOL7tQFybmTsRHQ",
	"BcYlohC5N3fSBqO5FIPdcJy6adjUSZyPTXvycO+Zhmu686mxZpJVrO3PLwBeVo+cFXthshZauuaZ1aZr",
	"+bsr6Dt28gbtf7Xpbyeffh3Nqn77x1VtYlr7Q+5JdUGInYbU1DBz+ebKqigZTX+7lJpfZofTyXuzx84V",
	"wX4Tt5vl8mKVnED/JWFKqUHup4cSH277foMn0Ja96eQAwcTUlwTkp1zgY51g9vgXE38qlGD6K02o9Db3",
	"vFMR336cisLN1WUswOfqguVJlo4xOUIkubr8/tgMO6o5/DBQfbhD37Cu51nHi4hqvpA9OInGSb7lR9It",
	"54VjOJE92Kc9EQYpeXTtjul67MaFYrlYxpx3GqZtNCytoi0Wy8VFRvttyjtOhrqz5TSpxBvOVI2mxs1q",
	"Cq2mET35iCfPCQY/pdIcUpmijw7i0CXVRVczdDCXEun9mlbRPuBT6NnL7EvlpVzVn4L81DCcF0ejl8oL",
	"0zArXr+UuRqiCdem0az7s1/M3s9SUTd3dgx3l24yUV1j8mAMjS0PAYKis4YPssvVZeN8xCqmOP67rJ7g",
	"5piXr8kccYY+5oohmqJ6zMKUKX0popwQ6Ok29A3tQ0yN01mx+xFj8L78TAWZXswSMZZdzBzjARtqArr5",
	"u893fyQdOnJvMkUUkUZnXuPxg/Lje05t9yfc7f20K7KcsUUrC/jYy1oTiVp+MydQfCnvyo5DgVyE2PRD",
	"ZsUZEYqR4Hooz07r1F+O4CuXrsx+ZfwK/j+sItUatcqttUxNfTWpLFW+T4F2ucewfU4NpnrgOSWY/gsW",
	"VYAR388lW2IKidCV8qd+djLWQ1jjyXtwQiXJ7KEoonunKfJtqowqTNNud7ypum26GgxhOHcB5pxHmBk2",
	"XisxfvccizIcs5Pc70bANuBBZxZkWKu8YYyZHA78lyEmR5HlIcw/E2jhbFKuezd96Z1i9eeT9ilp+X+A",
	"T9lBzsEYRimkOEI+WzrPR9G8Lwe1srtnJcOttRYex3SR/dGv2TAuJ/PK+C+BqLHDMXOmeYQs+ruKlxEz",
	"1nSt6dYVXfcqpZLRsIpes1GtNzeKao5QurOgtfTx3VZ8Y8uyt1icd6PhL3mArilmbeTx+/PTNlyLnfPz",
	"lAMSnywdoumUuLm6rEU3/+zu1lrr3wEAAP//KE54mWIpAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
