// Package profileapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package profileapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// ChangePhoneConfirmRequest Подтверждение смены номера телефона.
type ChangePhoneConfirmRequest struct {
	// Code OTP-код из SMS (4–6 цифр).
	Code string `json:"code"`

	// NewPhone Новый номер телефона в формате E.164.
	NewPhone string `json:"new_phone"`
}

// ChangePhoneRequestCodeRequest Запрос на отправку OTP-кода для смены номера телефона.
type ChangePhoneRequestCodeRequest struct {
	// NewPhone Новый номер телефона в формате E.164.
	NewPhone string `json:"new_phone"`
}

// Client Клиент сервиса. Аутентифицируется по номеру телефона (логин в формате E.164). Сразу после регистрации (verify-code, is_new=true) name ещё не задан — пустое/отсутствующее имя означает незавершённую регистрацию (дозаполняется через PATCH /profile).
type Client struct {
	// CreatedAt Дата и время регистрации клиента.
	CreatedAt time.Time `json:"created_at"`

	// Id Идентификатор клиента.
	Id openapi_types.UUID `json:"id"`

	// Name Имя клиента. Отсутствует у только что зарегистрированного клиента до шага 3 (PATCH /profile).
	Name *string `json:"name,omitempty"`

	// Phone Номер телефона в формате E.164. Используется как логин.
	Phone string `json:"phone"`
}

// Error Стандартное тело ошибки.
type Error struct {
	// Code Машинный код ошибки, например: slot_full, double_booking, slot_cancelled, slot_started, already_cancelled, invalid_code.
	Code string `json:"code"`

	// Details Необязательные машиночитаемые детали для динамических сообщений на клиенте (foundations §6): например, актуальная доступность для E1/E2, чтобы показать «Свободно: N мест» / «Свободно: M досок» без разбора текста message.
	Details *struct {
		// AvailableRentalBoards Сколько прокатных досок реально свободно (для нехватки прокатных досок).
		AvailableRentalBoards *int `json:"available_rental_boards,omitempty"`

		// AvailableSeats Сколько мест реально свободно на момент ошибки (для slot_full / превышения мест).
		AvailableSeats *int `json:"available_seats,omitempty"`
	} `json:"details,omitempty"`

	// Message Человекочитаемое сообщение об ошибке.
	Message string `json:"message"`
}

// RequestCodeResponse Ответ на запрос OTP-кода. В демонстрационной backend-реализации code возвращается в ответе вместо отправки через SMS-провайдера.
type RequestCodeResponse struct {
	// Code OTP-код для демонстрационной реализации без SMS-провайдера. В production должен отправляться через провайдера и не возвращаться клиенту.
	Code *string `json:"code,omitempty"`

	// ResendAfterSeconds Через сколько секунд можно запросить повторную отправку.
	ResendAfterSeconds int `json:"resend_after_seconds"`

	// TtlSeconds Срок жизни кода в секундах.
	TtlSeconds int `json:"ttl_seconds"`
}

// UpdateProfileRequest Запрос на обновление профиля.
type UpdateProfileRequest struct {
	// Name Имя клиента.
	Name string `json:"name"`
}

// BadRequest Стандартное тело ошибки.
type BadRequest = Error

// Conflict Стандартное тело ошибки.
type Conflict = Error

// InternalError Стандартное тело ошибки.
type InternalError = Error

// TooManyRequests Стандартное тело ошибки.
type TooManyRequests = Error

// Unauthorized Стандартное тело ошибки.
type Unauthorized = Error

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = UpdateProfileRequest

// ConfirmPhoneChangeJSONRequestBody defines body for ConfirmPhoneChange for application/json ContentType.
type ConfirmPhoneChangeJSONRequestBody = ChangePhoneConfirmRequest

// RequestPhoneChangeCodeJSONRequestBody defines body for RequestPhoneChangeCode for application/json ContentType.
type RequestPhoneChangeCodeJSONRequestBody = ChangePhoneRequestCodeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Удалить аккаунт
	// (DELETE /profile)
	DeleteAccount(w http.ResponseWriter, r *http.Request)
	// Получить профиль
	// (GET /profile)
	GetProfile(w http.ResponseWriter, r *http.Request)
	// Обновить имя
	// (PATCH /profile)
	UpdateProfile(w http.ResponseWriter, r *http.Request)
	// Подтвердить смену телефона
	// (POST /profile/phone/confirm)
	ConfirmPhoneChange(w http.ResponseWriter, r *http.Request)
	// Запросить код для смены телефона
	// (POST /profile/phone/request-code)
	RequestPhoneChangeCode(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Удалить аккаунт
// (DELETE /profile)
func (_ Unimplemented) DeleteAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить профиль
// (GET /profile)
func (_ Unimplemented) GetProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить имя
// (PATCH /profile)
func (_ Unimplemented) UpdateProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Подтвердить смену телефона
// (POST /profile/phone/confirm)
func (_ Unimplemented) ConfirmPhoneChange(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Запросить код для смены телефона
// (POST /profile/phone/request-code)
func (_ Unimplemented) RequestPhoneChangeCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteAccount operation middleware
func (siw *ServerInterfaceWrapper) DeleteAccount(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdateProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmPhoneChange operation middleware
func (siw *ServerInterfaceWrapper) ConfirmPhoneChange(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmPhoneChange(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestPhoneChangeCode operation middleware
func (siw *ServerInterfaceWrapper) RequestPhoneChangeCode(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestPhoneChangeCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/profile", wrapper.DeleteAccount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/profile", wrapper.GetProfile)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/profile", wrapper.UpdateProfile)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/profile/phone/confirm", wrapper.ConfirmPhoneChange)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/profile/phone/request-code", wrapper.RequestPhoneChangeCode)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaXW8bx9X+K4N9cyEhK35IivKawXvh6HXaFHUiRA564ajCihxJm5C77O7SiRoQoMS4",
	"liE1SlIDCYImgdMLX/SGokWLovgB+Bec+Qv5JcU5M7s7Sy4l2VWaFuiNrSV3Zs7nc85zhp8aRbdSdR3u",
	"BL5R+NTwuF91HZ/Tw5tW6T3+hxr3A3wquk7AHfrTqlbLdtEKbNfJfui7Dn7GP7Eq1TKXb5a4UTA2rNK6",
	"p9abRoX7vrWFn8N30IE2dEQDBuIAOgxG0BINaEEfOmJPNMQBg1NowUg0YCh2oZVh8AP+LVeJQ7GHq3ow",
	"FA3RgA70xB4M8FWxJw5xuw59fAItGOAZ4j5uOICWeAAdGEAXzjJG3TT84javWCjyKx7fNArG/2Rjc2Tl",
	"t372lue5nlGv102jxP2iZ1dR8ZdShM2gFPTcpZcaJvO5FfjrRbfmBAzaMMB9TqCLr0ELTmGIS1g+k1lg",
	"0IVz6DKPO4FVDpccwxDOxaHYh46+1yxpuOw6m2W7+HIO9MtusL5ZK5cN1Dyw7DKFhXXPssvWRpmvK0E2",
	"XMsr+UYhb2rfkShGIVcfc32LQVscwDHZaYBugz4Tu3AOQ+lWMgD5Elr06a44xBfaMCRdT0KPov12xd41",
	"ebIlGqKJRqT46KCtB9Amf6IvBigO+6nxiAQUexdJFPpJ+h160ML4lK+cUCAMocdmwniGY9GEHp33dNbE",
	"V3DjM4rXI0aWGsIAAzvcFleKPQz/8CW0XZ9kb5E93nYC7jlWWWr8Ms631Q7rnLZIePEJHj6H/5AwYh/9",
	"JD1HXuthwsJQ6Y/qnUnfdsRD8SUj159KPU7hGXSuxYVfwUA0MevIDANxJO2yD104Rh+gx9DabegSpuCZ",
	"d1z3tuXsKJTzX8pQgeuuVyxnJ8Q6P2mrx+gzsY9oBX0MEYz4p2guHRmG0FY2Cx3blRYbkRkPxB70RPO6",
	"TZaUTTyAFkEoQZkmnTiQgT8i27bFgUwThquhj5LKAByRY9sYy2z19uoc7XuCOrEZ3E88JK1a9HYM08ek",
	"b4thaOMX+CB2xf1oMQHg6u3V2UkTYVb0YQjP0KwqAglYFCB63OdOad3aDLi37vOi65R8NiN2oZ+RMrcp",
	"mcdQWgnekhj6vmPVgm3Xs//ISy8VITV9g0Rw/CgNIJpUL3YxYluxemSzP0FXHJHicVFT2XQCHTgjoGzL",
	"cME6QKXoDPMQkYfc1Jb6PcVCQaDTgw67qUQi4a8lmr4nFZr07x60pVIRaA2iWoky6eKlaAzdjFGPRKK8",
	"XN62nC2+su06HIua7VW03mRMEgySE+XcBjwjQ0lUR8/jA1ZmKj30RotJ60FHfCbrbcYwjarnVrkX2NyP",
	"fTl+1Lt3VlSYo6KnGKVsZvGnxl+WGHnuM9GYxb2ioDDy8wuLuLkVIL4aBeP3H3xQ+nTRXKq/YphGsFOl",
	"yht4trOFTnH4x+tVVDpFze8oF9DbsS4TmqD78W/RgD4Vog67lckvLSalevX1GzduoGivLb0+Lt2rd/Nz",
	"N9ZQyryZX0wTs24aCH62hwlyV5PZlGZbi1a4Gx/yYkCdSexP5chlt8Sn+/TrOEMlICQhRzRZ7Av89gTO",
	"xdE/4e//bMOnWrxsK9gaU+dbAnK00t54kWTwBWa0/BLjGboU1w0dskYSepUhRHPSFDMEPE+xx5lmFgT3",
	"x7IzUIWOmkLC8w4updLUCPGBzdzjnr25M4cBZjLbX3f4x/8XeDU+yxyrwsNeQ7aTCH/EBsJC1iSMGkIn",
	"i2GUhC3xuXgIHdkC9qmJiMhDS0IaYtkpxR3quy++pIajKT5PFVZ8zmaoklGRIRAeiKPIfMhJaNkpW7l5",
	"Z/nXLFv13E27zGdTQMjjVsBL61aaGx+ROWUdbdOOKP0U80EvdroM/03Xq+C+RskK+FxgV3gaHtmllJO/",
	"kQgbRojqeIeicdExtZpdSkU8q8JTzyBfJPdjU4qOjEHiRYgITDyQzeop9fO6PbqKV4ZchDqzxCHUszOx",
	"TxW0xRbYTIqb4oSGb+RuWOitT37Lna1g2yjkcznTqNhO9Jyi+EVo84IQw+AbsStjTRxiQsXJ2sP+nMX5",
	"+DPCEfk3KgRx6KaBU0RUxltUIhQDzF7RkDRfsoyO5Bxxg9+9as2Gv0KLVg1UrxQWcG0vk40T9QKL6LDJ",
	"Sm4NOe6G635kO1um/KpoOUVeLvOSevYDywvwySp73Crt6C/Yzj2rbJfWUcKkB3TSPREiGgtPGUUg1Tqi",
	"GNd7wQ6j4JAKD8UD2YMTOhyoLlJR7W5YNWn+MKA5RpfgaRdtIu4zYip4zMNwjqJqsZ4xHTaz6dacEnWW",
	"Pnv+ZGm2wCbnHhiHYk808WgUVRLZEzXGacJIH+lIuW7ls7fmTZXNcIxFfSQJttRaHLLnf4fHOjGHYYG9",
	"EzHz5+csm/rKbY2ZPz9ncEx4LMtRRFDIrD05mWCqi58MuqnjkcnYpsALMeriaQHBVmip4dj0AYZUYch1",
	"A+iI+zS42CMiduG2SeyKQQnJ/xb3MOQmJjqXqREOQS6TWAZOX4Ib9R56AkYKRfnAshMMFKlRdGBSl/lJ",
	"XeopsBNxsQmtnkiEwRpPk0YtbyQEjadCBxuFY12JzlhleHzBxEif4skJU+ZSfCV4i3VIg9VEay1Huym6",
	"fh8TYXKKxoYTXXWGwVeSdvZpJKW3FENVQM/YhlX8iDuluTAAdFrHUGZGdjilJqUlHsquSlantsbK0RLt",
	"0EIS65MzBq1zonHDKKrlZ4RqjZfjcREGXqxmqnoKOKaKgwasem6pVsSDKRPhHJ5JIqzrdy6OEM/GO8S0",
	"TZmi1xNmjTbQ4Vk0J/noa0svwEjTRirp+aNkpuqh9WK7hKJNLOqJ4Y0+g+mGk3xt0kkN9jjrSyizlEtD",
	"sCAoXyDnYwmPDJ6RIweyN1Yksp2QFlrifuK8hVwuFWb0JNVPn2K8tMR9v4pt+IpsMV+IFcMxBWgbG8UQ",
	"mOQr2Jqfi6MUrvsCLfe1NLvjvBXPn7RC3TR8Xqx5drCzWtzmFSnsBrc87t2s4c7h01shqfjN7+4YE4Op",
	"H6NZE7HbXYwvavGQw6NXv9SYrGKdK++u3mFZqxZsZzWimZzDxesun7AV2JskKfuglsstFAP3I+7Qn9RB",
	"0JyL7szopTjttoOgKodttrPppo26NM8ejvmqwKJ86hPNbZjRQIRgQ/3ZTXw8STJGkhMN4QSZuRpzmUw0",
	"iVNrYdaCHjUazYiePVEj5aRoChGQa91ceXts5qCAgB66MqjxYxipPkz2pk9DfH0qmnAetv+BHYSlNmVB",
	"D85FE47pzJ8aj5jKLsM07nHPlwbNZ3KZHCagW+WOVbWNgrGQyWUWJEBuUwSGzE+6o8yDtOT52yXGYfIm",
	"pyMa1EkMwlYp7NC0q8skHZ2hrgMB8JjAsId7/QCPYGCyd956by6fz9J/82+w1eX35nK517EFzyyY7Oby",
	"XC73v7MZBl/QlWkX2iFDSJhcHt2ky4EGzUMozE0tfTDotQlIXMIzDB7pY2nVzoQy06l9GL4hsT19SBtV",
	"Asla2nqDkMY2xL4qEWgKpTN1g4hxlH1vl4yC8f/kqptFuh6VWBzfdc/nFlOc+IXuMyYJknIMtoBaAoiD",
	"i8xDmYVRtZjLTxuwR+JkExcOxPo2rVo5uHxh8taP8LNWqVjejh6QqrQmwhFTx9ryEYvDpFirm8YWnzJn",
	"ik0gKVGTuuCU2clMcgwjOUBXBep8ipN+xYM4Lcc8lLvC7cvVLjHUKDTtFuMiQP2FPfgDmbIpqQi1R7qs",
	"U3xYtYLidiprm6wDYfs6LTdlNyCv5frkW61SqB5Ukrl4vAmn1KfuisMUbye6HEM2BdwP3nRLO9fm69RO",
	"qp5sQQKvxuu/TLx9H/drao5MI6nRpWGYuzyatB/w/LKRGyupIpcm66kRWzej+pql2WG2KK/7UISqe8X7",
	"vmhQn3JRo4UwXTlrDqCwZXRsSt+bjF11CylvJOky62cK4Ok3n/+N4itG8WLuxuWLot9KXStgx3F5ooI/",
	"upOcvCi7YkaoKJsLZxlT0uLHBDzTzVc09jcl2fkz1ec+iqIRg1F6PoWzhDh71I23XJWabDPT+zHlVC2B",
	"luVA62dOopTr5n9xIqVN5dKy6lsaSIkm3eV0xL6ckyTGRHJyNNX+/9ZJtjh/hQXjP9G6tuT8enLclBgA",
	"aj8duFqaauMKo3A3Oai4u1Zfw689ZJr0bdLVK/FMMPqpFc2goCfpwxwMoUfX7s9CnmSYRs0rqyGBX8hm",
	"raqd8WvVYrm2kVEzmuy9vFE3x09bDawt29mio1A3dRnepsH2FQ7y5fq5aQeuRfZ5oXmFEV7+Rlatr9X/",
	"EQAA//+IAHMaoiwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
